function tau_computed = Tau_computed(theta_1,theta_2,theta_dot1,theta_dot2,theta_dotdot1,theta_dotdot2,x_dotdot,y_dotdot)
%TAU_COMPUTED
%    TAU_COMPUTED = TAU_COMPUTED(THETA_1,THETA_2,THETA_DOT1,THETA_DOT2,THETA_DOTDOT1,THETA_DOTDOT2,X_DOTDOT,Y_DOTDOT)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    23-Oct-2015 18:44:57

t2 = theta_1-theta_2;
t3 = sin(t2);
t4 = cos(t2);
t5 = cos(theta_1);
t6 = sin(theta_2);
t7 = cos(theta_2);
t8 = sin(theta_1);
t9 = theta_dot1.^2;
t10 = theta_dot2.^2;
t11 = t5.*t6;
t18 = t7.*t8;
t12 = t11-t18;
t13 = 1.0./t12;
t14 = theta_dotdot2.*7.114931764705883e-2;
t15 = t5.*y_dotdot.*(1.11e2./2.5e2);
t16 = t6.*x_dotdot.*(1.11e2./2.5e2);
t17 = t4.*theta_dotdot1.*5.585519999999999e-2;
t19 = t7.*2.5e1;
t20 = y_dotdot.*(6.0./5.0);
t21 = t8.*t9.*7.548e-2;
t22 = t6.*t10.*7.548e-2;
t33 = t5.*theta_dotdot1.*7.548e-2;
t34 = t7.*theta_dotdot2.*7.548e-2;
t23 = t20+t21+t22-t33-t34;
t24 = t6.*2.5e1;
t25 = x_dotdot.*(6.0./5.0);
t26 = t5.*t9.*7.548e-2;
t27 = t7.*t10.*7.548e-2;
t28 = t8.*theta_dotdot1.*7.548e-2;
t29 = t6.*theta_dotdot2.*7.548e-2;
t30 = t25+t26+t27+t28+t29;
t31 = t3.*t9.*5.58552e-2;
t32 = t7.*y_dotdot.*(1.11e2./2.5e2);
t35 = t5.*t13.*t23.*(1.0./2.0);
tau_computed = [t14+t15+t16+t17-theta_dotdot1.*7.114931764705883e-2-t3.*t9.*5.58552e-2-t3.*t10.*5.58552e-2-t4.*theta_dotdot2.*5.585519999999999e-2-t8.*x_dotdot.*(1.11e2./2.5e2)-t7.*y_dotdot.*(1.11e2./2.5e2)-t13.*t23.*(t19-t3.*t5.*3.7e1).*(1.0./5.0e1)+t13.*t30.*(t24-t3.*t8.*3.7e1).*(1.0./5.0e1);-t14-t15-t16-t17+t31+t32+theta_dotdot1.*7.114931764705883e-2+t3.*t10.*5.58552e-2+t4.*theta_dotdot2.*5.585519999999999e-2+t8.*x_dotdot.*(1.11e2./2.5e2)-t13.*t23.*(t19+t3.*t5.*3.7e1).*(1.0./5.0e1)+t13.*t30.*(t24+t3.*t8.*3.7e1).*(1.0./5.0e1);-t14-t16-t17+t31+t32+t35-t8.*t13.*t30.*(1.0./2.0);t14+t16+t17-t31-t32+t35-t8.*t13.*t30.*(1.0./2.0)];
