function out1 = B_inverse(theta_1,theta_2)
%B_INVERSE
%    OUT1 = B_INVERSE(THETA_1,THETA_2)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    23-Oct-2015 18:44:57

t2 = sin(theta_2);
t3 = sin(theta_1);
t4 = cos(theta_1);
t5 = t2.*t4;
t6 = cos(theta_2);
t12 = t3.*t6;
t7 = t5-t12;
t8 = 1.0./t7;
t9 = theta_1-theta_2;
t10 = sin(t9);
t11 = t2.*2.5e1;
t13 = t6.*2.5e1;
t14 = t4.*t8.*(1.0./2.0);
out1 = reshape([t8.*(t11-t3.*t10.*3.7e1).*(1.0./5.0e1),t8.*(t11+t3.*t10.*3.7e1).*(1.0./5.0e1),t3.*t8.*(-1.0./2.0),t3.*t8.*(-1.0./2.0),t8.*(t13-t4.*t10.*3.7e1).*(-1.0./5.0e1),t8.*(t13+t4.*t10.*3.7e1).*(-1.0./5.0e1),t14,t14,-1.0e2./1.7e1,1.0e2./1.7e1,0.0,0.0,1.0e2./1.7e1,-1.0e2./1.7e1,-1.0e2./1.7e1,1.0e2./1.7e1],[4, 4]);
