function q_desired = q_desired(t)
%Q_DESIRED
%    Q_DESIRED = Q_DESIRED(T)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    23-Oct-2015 18:44:57

t2 = t.^2;
t3 = t.*(-5.962903085341577e-2+2.371987650120604e-6i);
t4 = t2.*(-5.852844090351766e-3+1.626321818526859e-2i);
t5 = t3+t4+6.91438182812328e-1+1.170308230674629e-1i;
t6 = angle(t5);
q_desired = [t.*6.91438182812328e-1-t2.*2.981451542670789e-2-t.*t2.*1.950948030117255e-3;t.*1.170308230674629e-1+t2.*1.185993825060302e-6+t.*t2.*5.421072728422863e-3;t6;pi.*(1.0./3.0)+t6];
